import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CartDrawerWrapper from "@/components/cartdrawerwrapper";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import localFont from "next/font/local";
import Providers from "./providers";

const retroFloral = localFont({
  src: "../public/fonts/Retro Floral.ttf",
  variable: "--font-retro-floral",
});

const moglanDemo = localFont({
  src: "../public/fonts/Moglan_DEMO.ttf",
  variable: "--font-moglan-demo",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Khaati Aarot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${retroFloral.variable} ${moglanDemo.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          {children}
          <CartDrawerWrapper />
        </Providers>
        <ToastContainer />
      </body>
    </html>
  );
}
